### ISSUE TITLE
Rename repo to mellanox.onyx

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/mellanox.onyx#1]
##### SUMMARY

Hi, can we please rename the repo to be consistent with others under gh/anisble-collections?

GitHub will maintain redirects. Once done we should review README and galaxy.yml

**Comment by samerd** [comment]
Thanks gundalow.
sure will do

**Comment by samerd** [comment]
In fact, I do not know how to do it.
could you guide me through that?

**Comment by gundalow** [comment]
I've renamed it, you'll want to update your `git remote` to point to the new URL, see https://help.github.com/en/github/administering-a-repository/renaming-a-repository

From a quick look at the repo:

For README.md you may wish to copy https://github.com/ansible-collections/collection_template/blob/master/README.md

For Basic CI copy https://github.com/ansible-collections/community.grafana/blob/master/.github/workflows/ansible-test.yml#L1-L24 and change https://github.com/ansible-collections/community.grafana/blob/master/.github/workflows/ansible-test.yml#L13 to be `path: ansible_collections/mellanox/onyx`

For galaxy.yml you may wish to base it on https://github.com/ansible-collections/community.grafana/blob/master/galaxy.yml

**Comment by gundalow** [comment]
@samerd Most welcome. Please shout out if you need a hand with any of this.
